name: NanoGaze Pipeline

on:
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - run: pip install -r requirements.txt

      - name: Run pipeline
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python src/pipeline.py
